db:
  image: postgres:9.5
  ports:
    - "5432:5432"

ruby-app:
  build: .
  dockerfile: Dockerfile
  environment:
    RAILS_ENV: development
  links:
    - db
  command: bundle exec rails server -p 3000 -b '0.0.0.0'
  volumes:
    - ".:/ruby-app"

  volumes_from:
    - bundle
  ports:
    - "3000:3000"

  volumes_from:
    - bundle

bundle:
  # 'image' will vary depending on your docker-compose
  # project name. You may need to run `docker-compose build web`
  # before this works.
  image: busybox
  volumes:
    - /bundle
