development: &development
  adapter: postgresql
  encoding: unicode
  database: gasof_development
  pool: 20
  username: postgres
  password:
  host: db

test:
  <<: *development
  database: gasof_test

